import { MD3LightTheme } from 'react-native-paper';
import { colors } from './colors';

export const theme = {
    ...MD3LightTheme,
    roundness: 4,
    colors: {
        ...MD3LightTheme.colors,
        primary: colors.primary,
        onPrimary: colors.onPrimary,
        primaryContainer: colors.primaryContainer,
        onPrimaryContainer: colors.onPrimaryContainer,
        secondary: colors.secondary,
        onSecondary: colors.primaryForeground,
        secondaryContainer: colors.secondaryContainer,
        onSecondaryContainer: colors.onSecondaryContainer,
        tertiary: colors.primary,
        onTertiary: colors.primaryForeground,
        tertiaryContainer: colors.tertiaryContainer,
        onTertiaryContainer: colors.onTertiaryContainer,
        error: colors.error,
        onError: '#FFFFFF',
        errorContainer: colors.errorContainer,
        onErrorContainer: colors.onErrorContainer,
        background: colors.background,
        onBackground: colors.foreground,
        surface: colors.surface,
        onSurface: colors.foreground,
        surfaceVariant: colors.surfaceVariant,
        onSurfaceVariant: colors.onSurfaceVariant,
        outline: colors.outline,
        outlineVariant: colors.outlineVariant,
        inverseSurface: colors.inverseSurface,
        inverseOnSurface: colors.inverseOnSurface,
        inversePrimary: colors.inversePrimary,
        elevation: {
            level0: 'transparent',
            level1: colors.surfaceContainerLow,
            level2: colors.surfaceContainer,
            level3: colors.surfaceContainerHigh,
            level4: colors.surfaceContainerHigh,
            level5: colors.surfaceContainerHighest,
        },
    },
};
